fix compiling with clang on windows
When compiling with clang on windows MSC_VER is defined and can conflict, leading to an unclear error (below). The real cause is the alignment macro which has accidentally used the MSVC compatible one instead of the clang compatible one.

```c++
cute_net.h(1663,24): error: default initialization of an object of const type 'const uint32_t [24]'
 static const uint32_t coeffs[24] __declspec(align(16)) = {
                       ^
cute_net.h(1663,34): error: expected ';' after top level declarator
 static const uint32_t coeffs[24] __declspec(align(16)) = {
                                 ^
                                 ;
cute_net.h(1663,57): error: expected unqualified-id
 static const uint32_t coeffs[24] __declspec(align(16)) = {
```